Automated and cleaned demo
oar-team/batsim pull request #46
Opened 2018-10-21 19:22 UTC by RaMdsC

2018-10-22 11:40 UTC, mickours requested changes
First, thanks a lot for this PR and welcome to the Batsim community!
Making the demo usable for everyone is very important for us, and your work is very valuable.
In order to make this perfect, some small changes are expected.

First the demo should contain the graph so the Github/Gitlab rendering permits to the newcomers to see the full demo without executing it.

Other remarcks are inline.

Tanks again :)

2018-10-22 11:40 UTC, mickours commented on demo/README.md
> +nix-env -i python3.6-jupyter-1.0.0
This is not necessary because it is already present in the `evalysNotebookEnv`, so it will be installed in the 5th step.

2018-10-22 11:40 UTC, mickours commented on demo/run.bash
> +  nix-env -i python3.6-jupyter-1.0.0
Same remark as for the README here: not needed.

2018-10-22 11:40 UTC, mickours commented on demo/run.bash
> +if ! nix-env -q 'batsim' &> /dev/null;
Not necessary to test if already installed: Nix will handle this by doing nothing it is already  intalled and by updating to the last version if necessary.

2018-10-22 13:08 UTC, mpoquet commented
Hello and welcome to Batsim's community @RaMdsC :). As @mickours said, thank you a lot for your work!

Can you remove the platform modifications from 73841bf? We try to keep batsim's master up-to-date with SimGrid and it looks like this commit reverts the platforms to the old SimGrid syntax. This probably comes from mistakes in our documentation, sorry for the inconvenience :(. The SimGrid version we currently use for batsim's master is defined [there in kapack's repo](https://github.com/oar-team/kapack/blob/master/simgrid/dev_working.nix). As I write these lines, it's SimGrid's commit f9b70a2e6b1e4076a895a8492e614c77d5eb4bf7 (2018-10-16).

2018-10-23 16:58 UTC, RaMdsC commented
Hi guys!

Thanks for the valuable feedback, cool how Nix automatically handles the updates :)
Also congratulations on the project, looking forward to using it for research purposes.

About the zone -> AS reversion, i did this since the demo was throwing an error when using 'zone' and 'zoneRoute', this error specifically:

`Invalid XML (XML input line 15, state 81): Unexpected character `<': `</platform>' expected.
[0.000000] /tmp/nix-build-simgrid-batsim.drv-0/simgrid/src/surf/xml/surfxml_sax_cb.cpp:57: [surf_parse/ERROR] Parse error at (null):15: Parse error in ../platforms/energy_platform_homogeneous_no_net_128.xml
[0.000000] /tmp/nix-build-simgrid-batsim.drv-0/simgrid/src/surf/xml/surfxml_sax_cb.cpp:59: [xbt/CRITICAL] Exiting now`

From the error i deduce that the version of Simgrid used by Batsim is the one given in 'simgrid-batsim' Nix package, which as you kindly pointed out, can be found on Kapack repo:
https://github.com/oar-team/kapack/blob/master/simgrid/batsim.nix

The fetch URL points to an alternative version of Simgrid, seemingly unmaintained:
https://github.com/freuk/simgrid

With Batsim i obtained the current Simgrid version and it confirms it:
`batsim --simgrid-version`
`3.13.91`

From the current Simgrid repo (https://github.com/simgrid/simgrid), the docs say the following:
New in DTD version 4.1 (in SimGrid 3.16): backward compatible change (v4 files are valid v4.1 files)
   - **\<zone\>** can be used as a synonym for the now deprecated \<as\>
   - **\<zoneRoute\>** can be used as a synonym for the now deprecated \<asroute\>
   - \<bypassZoneRoute\> an be used as a synonym for the now deprecated \<bypassAsRoute\>
   - \<actor\> can be used as a synonym for the now deprecated \<process\>

Looks like 3.13 does not have support for this. What do you guys think? Is this alternative version still needed or should we switch?

2018-10-25 13:09 UTC, mickours commented
Thanks for pointing that out, this due to the fact that the default version of batsim in Kapack is too old to work with the new platform files. We are in the middle of a transition between batsim 2 and 3 right now.

We have no time to make a proper release yet. But, as a workaround, switching to `batsim_dev` and `batsched_dev` version should make the demo works(without your patch on the platform).

Those versions still have some minor issues in some corner case, but except that,  (and the fact that we have great ambitions for the next release, but not enough manpower...) it is usable.

2018-11-10 08:06 UTC, merged